"""Fixed user-visible strings for router decisions (never generated by the LLM)."""

CANNED_REPLIES: dict[str, str] = {
    "emergency": (
        "It sounds like you might be experiencing a medical emergency. "
        "Please stop talking to this AI and immediately call your local emergency services "
        "(like 911 or 112) or go to the nearest hospital."
    ),
    "identity": (
        "I am DrHouseGPT, an AI-based medical assistant. "
        "I can help you clarify health questions and preventive medicine topics. "
        "⚠️ This information is educational and does not replace consultation with a doctor."
    ),
    "capabilities": (
        "I answer medical questions based on scientific literature, but I CANNOT "
        "provide official diagnoses, analyze your specific exams, or prescribe medication. "
        "Always consult a real doctor for personal health issues."
    ),
    "architecture": (
        "I use a specialized AI system that searches reliable medical documents "
        "before generating responses, ensuring my answers are grounded in scientific evidence."
    ),
    "bot_feelings": (
        "I'm a machine, so I don't have feelings. "
        "But I can help you figure out yours — is there something worrying you lately?"
    ),
    "thanks": (
        "That's great to hear — no need to thank me. "
        "I'm glad I could help. "
        "If you have another health or wellness question, ask anytime."
    ),
    "vague_symptom": (
        "I'm sorry you're not feeling well. I'm not a doctor, but I can share general health "
        "information. Could you say a bit more about what you're experiencing—for example, your "
        "main symptoms, how long this has been going on, and whether anything makes it better or "
        "worse? If you might be having an emergency, call your local emergency number right away."
    ),
    "off_topic": (
        "I focus on health, medicine, and wellness. "
        "If you have a question in those areas, ask away and I will do my best to help."
    ),
    "unclear": (
        "I'm not quite sure what you're asking. Could you rephrase your question?"
    ),
}


def canned_text(key: str | None) -> str:
    if not key or key not in CANNED_REPLIES:
        return CANNED_REPLIES["unclear"]
    return CANNED_REPLIES[key]


def validate_query(query: str) -> str | None:
    if not query or len(query.strip()) < 3:
        return "Please enter a valid question."
    return None
