name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: projectoec6101.azurecr.io
          username: ${{ secrets.projectoec6101 }}
          password: ${{ secrets.37GrmAxnvFVGUevikKYgPgHqV13oJzX9NbOcNPF7AF3xHZr8YubvJQQJ99CIACR0EKYEqg7NAAACAZCRszXV }}

      - name: Build Docker image
        run: |
          docker build -t projectoec6101.azurecr.io/projectoec:latest .

      - name: Push Docker image
        run: |
          docker push projectoec6101.azurecr.io/projectoec:latest
